### PR TITLE
Made adding formulas possible

### PR DESCRIPTION
**Pull request by Ghust1995**
Changed excel query so that if a cell is a formula, it can also be imported normally

### CODE REVIEW

**Comment by PedroMR** [comment]
Nice! Using formula-based values is a must. 👍

**Comment by kimsama** [comment]
Good job!

By the way it only deserializes single value from the given cell. 

Could you send me some kind of example spredsheet to make it more clear before merging it?

Thank you again.

**Comment by Ghust1995** [comment]
Yeah, for arrays or other stuff it would need a little more work. There could be a list of currently supported features on the read-me. I think however that generating stuff other than numbers (read arrays) would be kind of a weird process.

This is the spreadsheet that made me want to do the changes:
[Abilities.xlsx](https://github.com/kimsama/Unity-QuickSheet/files/580064/Abilities.xlsx)

**Comment by kimsama** [comment]
Merged the request. 

Yep, I saw the attached spreadsheet and that was what I guessed. Thanks for the great help.

Thank you again.

**Pull request merged**
