### PR TITLE
Change property drawers and gitignore

### PR DESCRIPTION
**Pull request by JohannesDeml**
Especially chaning the serialized propertie names from anme to display name makes everything more readable. The style also didn't look that good with the light skin.

Here is how it looks now:

grafik

### CODE REVIEW

**Comment by kimsama** [comment]
Hi, JohannesDeml

Great! Thank you for that all proceedings. I'll merge after review. 

Thank you again.

**Comment by JohannesDeml** [comment]
Sure, no thing. I might have been a bit harsh with the enum drawer and the background (by just removing those). 
As for the background: It didn't look good with the light skin.
As for the enum: I think it has to many fields. I didn't quite understand why you would want to expose so many.

Looking forward to your feedback :)

**Comment by kimsama** [comment]
I moved all example related files under Assets/QuickSheet/Example folder to make it easier to keep maintenance.

**Comment by JohannesDeml** [comment]
Nice, that sounds like a good idea!

**Pull request merged**
